### ISSUE TITLE
phase 1 task list

### ISSUE THREAD

**Issue by zhongyi80** [zhongyi80/PyDoReMi#1]
- [ ] import scan images
- [ ] implement optical music recognition (OMR)
- [ ] output blank music sheet in pdf format
